In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Kolkata_weather_data(2017-2022).csv", parse_dates=['Date time'], index_col='Date time')
df.head()

,Address,Minimum Temperature,Maximum Temperature,Temperature,Dew Point,Relative Humidity,Heat Index,Wind Speed,Wind Gust,Wind Direction,...,Visibility,Cloud Cover,Sea Level Pressure,Weather Type,Latitude,Longitude,Resolved Address,Name,Info,Conditions
Date time,,,,,,,,,,,,,,,,,,,,,
2017-01-01,"Kolkata,West Bengal,India",14.0,25.3,19.9,16.5,82.47,NaN,5.8,NaN,78.33,...,1.2,4.9,1015.9,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
2017-01-02,"Kolkata,West Bengal,India",16.0,26.0,20.6,16.0,76.76,NaN,8.1,NaN,148.54,...,1.4,0.3,1015.6,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
2017-01-03,"Kolkata,West Bengal,India",16.0,27.0,21.1,15.6,73.12,27.3,9.2,NaN,244.92,...,1.6,10.7,1014.7,"Mist, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
2017-01-04,"Kolkata,West Bengal,India",16.0,25.0,19.9,14.5,72.57,NaN,8.1,NaN,244.38,...,1.8,2.3,1014.6,"Mist, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
2017-01-05,"Kolkata,West Bengal,India",15.0,25.6,19.6,13.7,71.88,NaN,8.1,NaN,231.58,...,1.9,0.0,1013.7,"Mist, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear

### Checking values of Name

In [3]:
df['Name'].value_counts()

Name
Kolkata, WB, India    2191
Name: count, dtype: int64

In [4]:
df.drop(['Name'], axis=1, inplace=True)

In [5]:
print(df['Resolved Address'].value_counts())
print(df['Address'].value_counts())

Resolved Address
Kolkata, WB, India    2191
Name: count, dtype: int64
Address
Kolkata,West Bengal,India    2191
Name: count, dtype: int64

In [6]:
df.drop(['Resolved Address', 'Address'], axis=1, inplace=True)
df.head(10)

,Minimum Temperature,Maximum Temperature,Temperature,Dew Point,Relative Humidity,Heat Index,Wind Speed,Wind Gust,Wind Direction,Wind Chill,...,Precipitation Cover,Snow Depth,Visibility,Cloud Cover,Sea Level Pressure,Weather Type,Latitude,Longitude,Info,Conditions
Date time,,,,,,,,,,,,,,,,,,,,,
2017-01-01,14.0,25.3,19.9,16.5,82.47,NaN,5.8,NaN,78.33,NaN,...,0.0,0.0,1.2,4.9,1015.9,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-02,16.0,26.0,20.6,16.0,76.76,NaN,8.1,NaN,148.54,NaN,...,0.0,0.0,1.4,0.3,1015.6,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-03,16.0,27.0,21.1,15.6,73.12,27.3,9.2,NaN,244.92,NaN,...,0.0,0.0,1.6,10.7,1014.7,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-04,16.0,25.0,19.9,14.5,72.57,NaN,8.1,NaN,244.38,NaN,...,0.0,0.0,1.8,2.3,1014.6,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-05,15.0,25.6,19.6,13.7,71.88,NaN,8.1,NaN,231.58,NaN,...,0.0,0.0,1.9,0.0,1013.7,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-06,13.0,24.6,18.5,11.8,68.36,NaN,11.4,NaN,135.88,NaN,...,0.0,0.0,1.8,0.0,1013.9,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-07,11.0,25.3,17.8,11.5,70.19,NaN,8.1,NaN,136.92,NaN,...,0.0,0.0,1.7,2.1,1012.5,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-08,12.0,26.2,19.1,12.0,67.10,NaN,8.1,NaN,50.38,NaN,...,0.0,0.0,1.8,0.0,1012.3,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-09,13.0,27.0,20.0,12.9,67.08,26.8,5.8,NaN,27.46,NaN,...,0.0,0.0,1.9,0.0,1012.1,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear
2017-01-10,15.0,23.2,19.0,12.9,69.32,NaN,16.1,NaN,70.08,NaN,...,0.0,0.0,1.8,19.4,1013.0,"Mist, Smoke Or Haze",22.5705,88.3713,NaN,Clear

In [7]:
df.isnull().sum()

Minimum Temperature       0
Maximum Temperature       0
Temperature               0
Dew Point                 0
Relative Humidity         0
Heat Index              340
Wind Speed                0
Wind Gust              2100
Wind Direction            0
Wind Chill             2178
Precipitation             0
Precipitation Cover       0
Snow Depth              365
Visibility                0
Cloud Cover               0
Sea Level Pressure        1
Weather Type              1
Latitude                  0
Longitude                 0
Info                   2191
Conditions                0
dtype: int64

In [8]:
df.drop(['Wind Gust', 'Wind Chill', 'Info', 'Snow Depth'], axis=1, inplace=True)
df.columns

Index(['Minimum Temperature', 'Maximum Temperature', 'Temperature',
       'Dew Point', 'Relative Humidity', 'Heat Index', 'Wind Speed',
       'Wind Direction', 'Precipitation', 'Precipitation Cover', 'Visibility',
       'Cloud Cover', 'Sea Level Pressure', 'Weather Type', 'Latitude',
       'Longitude', 'Conditions'],
      dtype='object')

In [9]:
df.head(10)

,Minimum Temperature,Maximum Temperature,Temperature,Dew Point,Relative Humidity,Heat Index,Wind Speed,Wind Direction,Precipitation,Precipitation Cover,Visibility,Cloud Cover,Sea Level Pressure,Weather Type,Latitude,Longitude,Conditions
Date time,,,,,,,,,,,,,,,,,
2017-01-01,14.0,25.3,19.9,16.5,82.47,NaN,5.8,78.33,0.0,0.0,1.2,4.9,1015.9,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-02,16.0,26.0,20.6,16.0,76.76,NaN,8.1,148.54,0.0,0.0,1.4,0.3,1015.6,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-03,16.0,27.0,21.1,15.6,73.12,27.3,9.2,244.92,0.0,0.0,1.6,10.7,1014.7,"Mist, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-04,16.0,25.0,19.9,14.5,72.57,NaN,8.1,244.38,0.0,0.0,1.8,2.3,1014.6,"Mist, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-05,15.0,25.6,19.6,13.7,71.88,NaN,8.1,231.58,0.0,0.0,1.9,0.0,1013.7,"Mist, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-06,13.0,24.6,18.5,11.8,68.36,NaN,11.4,135.88,0.0,0.0,1.8,0.0,1013.9,"Mist, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-07,11.0,25.3,17.8,11.5,70.19,NaN,8.1,136.92,0.0,0.0,1.7,2.1,1012.5,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-08,12.0,26.2,19.1,12.0,67.10,NaN,8.1,50.38,0.0,0.0,1.8,0.0,1012.3,"Mist, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-09,13.0,27.0,20.0,12.9,67.08,26.8,5.8,27.46,0.0,0.0,1.9,0.0,1012.1,"Mist, Smoke Or Haze",22.5705,88.3713,Clear
2017-01-10,15.0,23.2,19.0,12.9,69.32,NaN,16.1,70.08,0.0,0.0,1.8,19.4,1013.0,"Mist, Smoke Or Haze",22.5705,88.3713,Clear

In [10]:
import mysql.connector
cnx = mysql.connector.connect(user ='root', password='12345', host='localhost', database='kolkata_weather')

In [11]:
from sqlalchemy import create_engine, text
engine = create_engine('mysql+pymysql://root:12345@localhost/kolkata_weather')

In [12]:
df.to_sql(name='weather', if_exists = 'replace', con=engine)

2191

In [13]:
with engine.connect() as conn:
   query = "ALTER TABLE weather ADD PRIMARY KEY (`Date time`)"
   conn.execute(text(query))

In [14]:
df.to_csv("Kolkata_weather_data(2017-2022)_processed.csv")